CREATE TABLE [dbo].[DimDeliveryGroup] (

	[DeliveryGroupSk] int NOT NULL, 
	[DeliveryGroupBk] varchar(18) NOT NULL, 
	[Name] varchar(255) NULL, 
	[ShortName] varchar(80) NULL, 
	[CurrencyIsoCode] varchar(3) NULL, 
	[ExpectedStartDate] datetime2(6) NULL, 
	[ExpectedEndDate] datetime2(6) NULL, 
	[AccountSk] int NULL, 
	[BillingAccountSk] int NULL, 
	[ForecastStatusSk] int NULL, 
	[ProposalSk] int NULL, 
	[DeliveryProgram] varchar(80) NULL, 
	[DeliveryStage] varchar(80) NULL, 
	[DeliveryStatus] varchar(80) NULL, 
	[LostReason] varchar(50) NULL, 
	[LostReasonNarrative] varchar(255) NULL, 
	[ProbabilityCodeEnum] varchar(50) NULL, 
	[ExternalEngagementReference] varchar(255) NULL, 
	[ForecastAtThisLevel] varchar(10) NULL, 
	[Reference] varchar(100) NULL, 
	[RiskLevel] varchar(255) NULL, 
	[ActualUsage] decimal(18,2) NULL, 
	[BaselineContractCost] decimal(18,2) NULL, 
	[BaselineContractMargin] decimal(18,2) NULL, 
	[BaselineContractMarginAmount] decimal(18,2) NULL, 
	[BaselineContractRevenue] decimal(18,2) NULL, 
	[BaselineExpensesContractCost] decimal(18,2) NULL, 
	[BaselineExpensesContractMargin] decimal(18,2) NULL, 
	[BaselineExpensesContractMarginAmount] decimal(18,2) NULL, 
	[BaselineExpensesContractRevenue] decimal(18,2) NULL, 
	[BaselineServicesContractCost] decimal(18,2) NULL, 
	[BaselineServicesContractMargin] decimal(18,2) NULL, 
	[BaselineServicesContractMarginAmount] decimal(18,2) NULL, 
	[BaselineServicesContractRevenue] decimal(18,2) NULL, 
	[BaselineUsage] decimal(18,2) NULL, 
	[ContractCost] decimal(18,2) NULL, 
	[ContractMargin] decimal(18,2) NULL, 
	[ContractMarginAmount] decimal(18,2) NULL, 
	[ContractRevenue] decimal(18,2) NULL, 
	[ExpensesContractCost] decimal(18,2) NULL, 
	[ExpensesContractMargin] decimal(18,2) NULL, 
	[ExpensesContractMarginAmount] decimal(18,2) NULL, 
	[ExpensesContractRevenue] decimal(18,2) NULL, 
	[ExpensesSupplierInvoiceableAmount] decimal(18,2) NULL, 
	[ForecastUsage] decimal(18,2) NULL, 
	[InvoicingCcyExpensesInvoiceableAmount] decimal(18,2) NULL, 
	[InvoicingCcyServicesInvoiceableAmount] decimal(18,2) NULL, 
	[InvoicingCurrencyContractRevenue] decimal(18,2) NULL, 
	[InvoicingCurrencyIsoCode] varchar(3) NULL, 
	[KC_IsActive] bit NULL, 
	[KC_IsWon] bit NULL, 
	[KC_Trigger] bit NULL, 
	[ProposalItemsCostTotal] decimal(18,2) NULL, 
	[ProposalItemsMargin] decimal(18,2) NULL, 
	[ProposalItemsMarginAmount] decimal(18,2) NULL, 
	[ServicesContractCost] decimal(18,2) NULL, 
	[ServicesContractMargin] decimal(18,2) NULL, 
	[ServicesContractMarginAmount] decimal(18,2) NULL, 
	[ServicesContractRevenue] decimal(18,2) NULL, 
	[ServicesSupplierInvoiceableAmount] decimal(18,2) NULL, 
	[SharedWithCustomer] bit NULL, 
	[WeightedContractRevenue] decimal(18,2) NULL, 
	[WhatIfDifference] decimal(18,2) NULL, 
	[UrlToKanataRevenuesAndCostsRecord] varchar(255) NOT NULL, 
	[UrlToKanataRecord] varchar(255) NOT NULL, 
	[_crda_ActiveFromDate] datetime2(6) NOT NULL, 
	[_crda_ActiveToDate] datetime2(6) NOT NULL, 
	[_crda_ActiveFromDateSk] int NOT NULL, 
	[_crda_ActiveToDateSk] int NOT NULL, 
	[IsCurrent] bit NOT NULL, 
	[_crda_Hash] varbinary(16) NOT NULL, 
	[_crda_CreatedExecutionId] int NOT NULL, 
	[_crda_CreatedDateTime] datetime2(6) NOT NULL, 
	[_crda_isDeleted] bit NOT NULL
);


GO
ALTER TABLE [dbo].[DimDeliveryGroup] ADD CONSTRAINT PK__dbo_DimDeliveryGroup primary key NONCLUSTERED ([DeliveryGroupSk]);
GO
ALTER TABLE [dbo].[DimDeliveryGroup] ADD CONSTRAINT UQ__dbo_DimDeliveryGroup unique NONCLUSTERED ([DeliveryGroupBk], [_crda_ActiveFromDate]);