CREATE TABLE [Internal].[DemandActivity] (
    [ActivityAssignmentBk]            VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
    [ActivityAssignmentDemandBk]      VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ResourceBk]                      VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [DemandStart]                     DATETIME2 (7)   NULL,
    [DemandEnd]                       DATETIME2 (7)   NULL,
    [DemandStartSk]                   AS              (CONVERT([int],CONVERT([varchar](8),[DemandStart],(112)))) PERSISTED,
    [DemandEndSk]                     AS              (CONVERT([int],CONVERT([varchar](8),[DemandEnd],(112)))) PERSISTED,
    [DemandStartMonthEnd]             DATE            NULL,
    [DemandEndMonthEnd]               DATE            NULL,
    [DemandStartMonthEndSk]           AS              (CONVERT([int],CONVERT([varchar](8),[DemandStartMonthEnd],(112)))) PERSISTED,
    [DemandEndMonthEndSk]             AS              (CONVERT([int],CONVERT([varchar](8),[DemandEndMonthEnd],(112)))) PERSISTED,
    [EarliestTimeEntryDate]           DATETIME2 (7)   NULL,
    [LatestTimeEntryDate]             DATETIME2 (7)   NULL,
    [ForecastP1EndDate]               DATETIME2 (7)   NULL,
    [ForecastP2EndDate]               DATETIME2 (7)   NULL,
    [ForecastP3EndDate]               DATETIME2 (7)   NULL,
    [IncludeInRollUp]                 BIT             NULL,
    [ResourcedActivityBk]             VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ActivityAssgnRoleBk]             VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ActivityAssignmentDemandRole]    VARCHAR (1024)  NULL,
    [ActivityRolePracticeBk]          VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [CandidateStatusBk]               VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ResourceLocationBk]              VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ActivityLocationBk]              VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ActivityDeliveryGroupBk]         VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [DeliveryGroupAccountBk]          VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [DeliveryGroupForecastStatusBk]   VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ActivityDemandStatusBk]          VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ResourcingStatusBk]              VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [CurrencyIsoCode]                 VARCHAR (3)     NULL,
    [RevenueRate]                     DECIMAL (18, 2) NULL,
    [TotalActualCost]                 DECIMAL (18, 2) NULL,
    [ForecastP1Cost]                  DECIMAL (18, 2) NULL,
    [ForecastP2Cost]                  DECIMAL (18, 2) NULL,
    [ForecastP3Cost]                  DECIMAL (18, 2) NULL,
    [TotalActualRevenue]              DECIMAL (18, 2) NULL,
    [ForecastP1Revenue]               DECIMAL (18, 2) NULL,
    [ForecastP2Revenue]               DECIMAL (18, 2) NULL,
    [ForecastP3Revenue]               DECIMAL (18, 2) NULL,
    [TotalActualUsage]                DECIMAL (18, 2) NULL,
    [ForecastP1Usage]                 DECIMAL (18, 2) NULL,
    [ForecastP2Usage]                 DECIMAL (18, 2) NULL,
    [ForecastP3Usage]                 DECIMAL (18, 2) NULL,
    [BaselineCost]                    DECIMAL (18, 2) NULL,
    [BaselineMargin]                  DECIMAL (18, 2) NULL,
    [BaselineMarginAmount]            DECIMAL (18, 2) NULL,
    [BaselineRevenue]                 DECIMAL (18, 2) NULL,
    [BaselineUsage]                   DECIMAL (18, 2) NULL,
    [BaselineUtilisationPercentage]   DECIMAL (18, 6) NULL,
    [AssignmentPercentage]            DECIMAL (18, 6) NULL,
    [DefaultCostRatePercentage]       DECIMAL (18, 6) NULL,
    [DefaultRevenueRatePercentage]    DECIMAL (18, 6) NULL,
    [DiscountPercentage]              DECIMAL (8, 3)  NULL,
    [UtilisationPercentage]           DECIMAL (12, 6) NULL,
    [ResourcedActivityBusinessUnitBk] VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ResourcedActivityTypeBk]         VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ActivityGroup]                   VARCHAR (1024)  NULL,
    [ResourceDeliveryElementBk]       VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [DemandRef]                       VARCHAR (255)   NULL,
    [ActivityAssignmentLogNotes]      VARCHAR (4000)  NULL,
    [_crda_Hash]                      BINARY (64)     NOT NULL,
    [_crda_CreatedExecutionId]        INT             NOT NULL,
    [_crda_CreatedDateTime]           DATETIME2 (7)   NOT NULL,
    [_crda_UpdatedExecutionId]        INT             NOT NULL,
    [_crda_UpdatedDateTime]           DATETIME2 (7)   NOT NULL,
    CONSTRAINT [UQ__Internal_DemandActivity] UNIQUE CLUSTERED ([ActivityAssignmentBk] ASC, [ResourceBk] ASC, [DemandStart] ASC)
);


GO

