CREATE TABLE [Internal].[DimDate] (
    [DateKey]             INT                 NOT NULL,
    [Date]                DATE                NOT NULL,
    [Day]                 TINYINT             NOT NULL,
    [DaySuffix]           CHAR (2)            NOT NULL,
    [Weekday]             TINYINT             NOT NULL,
    [WeekDayName]         VARCHAR (10)        NOT NULL,
    [IsWeekend]           BIT                 NOT NULL,
    [IsHoliday]           BIT                 NOT NULL,
    [IsBankHoliday]       BIT                 NOT NULL,
    [HolidayText]         VARCHAR (64) SPARSE NULL,
    [DOWInMonth]          TINYINT             NOT NULL,
    [DayOfYear]           SMALLINT            NOT NULL,
    [WeekOfMonth]         TINYINT             NOT NULL,
    [WeekOfYear]          TINYINT             NOT NULL,
    [ISOWeekOfYear]       TINYINT             NOT NULL,
    [Month]               TINYINT             NOT NULL,
    [MonthName]           VARCHAR (10)        NOT NULL,
    [Quarter]             TINYINT             NOT NULL,
    [QuarterName]         VARCHAR (6)         NOT NULL,
    [QuarterYear]         VARCHAR (7)         NOT NULL,
    [Half]                TINYINT             NOT NULL,
    [HalfName]            VARCHAR (6)         NOT NULL,
    [Year]                INT                 NOT NULL,
    [MMYYYY]              CHAR (6)            NOT NULL,
    [ShortMonthYear]      CHAR (8)            NOT NULL,
    [LongMonthYear]       CHAR (20)           NOT NULL,
    [TaxYear]             CHAR (7)            NOT NULL,
    [TaxQuarter]          TINYINT             NOT NULL,
    [FiscalYear]          INT                 NOT NULL,
    [FiscalQuarter]       TINYINT             NOT NULL,
    [WeekEnding]          DATE                NOT NULL,
    [FirstDayOfWeek]      DATE                NULL,
    [FirstDayOfWorkWeek]  DATE                NULL,
    [FirstDayOfMonth]     DATE                NOT NULL,
    [LastDayOfMonth]      DATE                NOT NULL,
    [FirstDayOfQuarter]   DATE                NOT NULL,
    [LastDayOfQuarter]    DATE                NOT NULL,
    [FirstDayOfHalf]      DATE                NOT NULL,
    [LastDayOfHalf]       DATE                NOT NULL,
    [FirstDayOfYear]      DATE                NOT NULL,
    [LastDayOfYear]       DATE                NOT NULL,
    [FirstDayOfNextMonth] DATE                NOT NULL,
    [FirstDayOfNextYear]  DATE                NOT NULL,
    [IsNonWorkDay]        AS                  (case when [IsWeekend]=(1) OR [IsBankHoliday]=(1) then (1) else (0) end),
    CONSTRAINT [PK__Internal_DimDate] PRIMARY KEY CLUSTERED ([DateKey] ASC)
);


GO

