CREATE TABLE [Internal].[DemandActivity] (

	[ActivityAssignmentBk] varchar(18) NOT NULL, 
	[ActivityAssignmentDemandBk] varchar(18) NULL, 
	[ResourceBk] varchar(18) NULL, 
	[DemandStart] datetime2(6) NOT NULL, 
	[DemandEnd] datetime2(6) NOT NULL, 
	[DemandStartSk] int NOT NULL, 
	[DemandEndSk] int NOT NULL, 
	[DemandStartMonthEnd] date NOT NULL, 
	[DemandEndMonthEnd] date NOT NULL, 
	[DemandStartMonthEndSk] int NOT NULL, 
	[DemandEndMonthEndSk] int NOT NULL, 
	[EarliestTimeEntryDate] datetime2(6) NULL, 
	[LatestTimeEntryDate] datetime2(6) NULL, 
	[ForecastP1EndDate] datetime2(6) NULL, 
	[ForecastP2EndDate] datetime2(6) NULL, 
	[ForecastP3EndDate] datetime2(6) NULL, 
	[IncludeInRollUp] bit NULL, 
	[ResourcedActivityBk] varchar(18) NULL, 
	[ActivityAssgnRoleBk] varchar(18) NULL, 
	[ActivityAssignmentDemandRole] varchar(1024) NULL, 
	[ActivityRolePracticeBk] varchar(18) NULL, 
	[CandidateStatusBk] varchar(18) NULL, 
	[ResourceLocationBk] varchar(18) NULL, 
	[ActivityLocationBk] varchar(18) NULL, 
	[ActivityDeliveryGroupBk] varchar(18) NULL, 
	[DeliveryGroupAccountBk] varchar(18) NULL, 
	[DeliveryGroupForecastStatusBk] varchar(18) NULL, 
	[ActivityDemandStatusBk] varchar(18) NULL, 
	[ResourcingStatusBk] varchar(18) NULL, 
	[CurrencyIsoCode] varchar(3) NULL, 
	[RevenueRate] decimal(18,2) NULL, 
	[TotalActualCost] decimal(18,2) NULL, 
	[ForecastP1Cost] decimal(18,2) NULL, 
	[ForecastP2Cost] decimal(18,2) NULL, 
	[ForecastP3Cost] decimal(18,2) NULL, 
	[TotalActualRevenue] decimal(18,2) NULL, 
	[ForecastP1Revenue] decimal(18,2) NULL, 
	[ForecastP2Revenue] decimal(18,2) NULL, 
	[ForecastP3Revenue] decimal(18,2) NULL, 
	[TotalActualUsage] decimal(18,2) NULL, 
	[ForecastP1Usage] decimal(18,2) NULL, 
	[ForecastP2Usage] decimal(18,2) NULL, 
	[ForecastP3Usage] decimal(18,2) NULL, 
	[BaselineCost] decimal(18,2) NULL, 
	[BaselineMargin] decimal(18,2) NULL, 
	[BaselineMarginAmount] decimal(18,2) NULL, 
	[BaselineRevenue] decimal(18,2) NULL, 
	[BaselineUsage] decimal(18,2) NULL, 
	[BaselineUtilisationPercentage] decimal(18,6) NULL, 
	[AssignmentPercentage] decimal(18,6) NULL, 
	[DefaultCostRatePercentage] decimal(18,6) NULL, 
	[DefaultRevenueRatePercentage] decimal(18,6) NULL, 
	[DiscountPercentage] decimal(8,3) NULL, 
	[UtilisationPercentage] decimal(12,6) NULL, 
	[ResourcedActivityBusinessUnitBk] varchar(18) NULL, 
	[ResourcedActivityTypeBk] varchar(18) NULL, 
	[ActivityGroup] varchar(1024) NULL, 
	[ResourceDeliveryElementBk] varchar(18) NULL, 
	[DemandRef] varchar(255) NULL, 
	[ActivityAssignmentLogNotes] varchar(4000) NULL, 
	[_crda_Hash] varbinary(16) NOT NULL, 
	[_crda_CreatedExecutionId] int NOT NULL, 
	[_crda_CreatedDateTime] datetime2(6) NOT NULL, 
	[_crda_UpdatedExecutionId] int NOT NULL, 
	[_crda_UpdatedDateTime] datetime2(6) NOT NULL
);


GO
ALTER TABLE [Internal].[DemandActivity] ADD CONSTRAINT UQ__Internal_DemandActivity unique NONCLUSTERED ([ActivityAssignmentBk], [ResourceBk], [DemandStart]);